name: Publish to Azure Artifacts

on:
  push:
    branches:
      - master
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
      AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>dts-public-azure-artifacts</id>
                <username>${AZURE_DEVOPS_ARTIFACT_USERNAME}</username>
                <password>${AZURE_DEVOPS_ARTIFACT_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Determine version from release or fallback
        id: determine_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION="${GITHUB_REF##*/}"
          else
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "release-17.0.0")
            VERSION=$(echo "$LATEST_TAG" | awk -F. '{$NF+=1; print $1"."$2"."$3}')
            VERSION="${VERSION}-SNAPSHOT"
          fi
          VERSION="${VERSION#release-}"
          echo "revision=$VERSION"
          echo "revision=$VERSION" >> $GITHUB_ENV

      - name: Publish using Azure Artifacts profile
        run: mvn --batch-mode clean deploy -Pazure-artifacts-pkg -Drevision=${{ env.revision }}
