name: Publish to Azure Artifacts

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
      AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>dts-public-azure-artifacts</id>
                <username>${AZURE_DEVOPS_ARTIFACT_USERNAME}</username>
                <password>${AZURE_DEVOPS_ARTIFACT_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Publish using Azure Artifacts profile
        run: mvn --batch-mode clean deploy -Pazure-artifacts-pkg
